Portfolio: Add contact form and pair programing
medijdir/portfolio_project pull request #4
Opened 2023-06-13 13:23 UTC by medijdir

for this task I have used: 
- GitHub 
- collaborate with a person
- Html and CSS

2023-06-13 14:17 UTC, divinecharlotte requested changes
Hi @medijdir     , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## To Highlight 💯 

- Use of GitHub flow👍 
- Descriptive pr 👍 

 




 
![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes ♻️


_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-13 14:17 UTC, divinecharlotte commented on index.html
> +    </section>
- [ ] Kindly consider sticking to the design templates in Figma as much as possible, this includes the font, colors, images, and spacing (margin/padding) to make your design an exact duplicate of the provided one in Figma because currently your whole page styling is messed up tru to fix it all but now am more focused on contact form part check the images below for more clarification 😄 
- your design 👇 
<img width="377" alt="Screen Shot 2023-06-13 at 16 02 45" src="https://github.com/medijdir/portfolio_project/assets/60146030/48a96763-bdd3-4201-bfcb-32f5a166887f">
- Figma Design 👇 
<img width="345" alt="Screen Shot 2023-06-13 at 16 06 50" src="https://github.com/medijdir/portfolio_project/assets/60146030/03b90e15-fba9-4a5a-9f10-4571253b5973">

2023-06-14 15:55 UTC, osamaashraf6 approved these changes
Hi @medijdir 😊, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![MinionsGIF (2)](https://github.com/noelfoka/portfolio-Microverse-version/assets/83360636/b36bdf2b-d078-4c67-96d2-49df215cf666)

## Highlights🎉🎉

- [ ] Following Figma Design 💯
- [ ] All input fields are wrapped in a single-form element🚀💯
- [ ] Message input has maxlength="500" attribute.👌💯
- [ ] All input fields have the required attribute to activate the validation on submission.👌


## Optional suggestions

- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 15:58 UTC, medijdir commented
thanks for all your advice and help

2023-06-14 15:58 UTC, merged